### ISSUE TITLE
Add `before_block` and `after_block` params for txns endpoints

### ISSUE THREAD

**Issue by edwardchew97** [Nearblocks/nearblocks#135]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We are currently using the txns endpoints for transaction history on Meteor Wallet and wanting to add this to MNW as well. However, there's a challenge now on pagination since we need to combine transactions from 3 different endpoints (txns, ft-txns and nft-txns) to show complete transaction history. It gets trickier when we need to do pagination. 

**Describe the solution you'd like**
Adding the block_height params to all of the mentioned endpoints so that querying and filtering txns can be much easier.

**Comment by andrewklau** [comment]
Closed by #275
