### ISSUE TITLE
Errors on Account Page

### ISSUE THREAD

**Issue by frol** [Nearblocks/nearblocks#149]
## Bug Report

**Current Behavior**

I often use NearBlocks, and almost every time I hit some error on first load and have to refresh the page. I tried both beta and regular domain.

<img width="1604" alt="image" src="https://github.com/Nearblocks/nearblocks/assets/304265/6ca8eeb4-d097-49bb-bd50-c1812bb22d07">

<img width="1604" alt="image" src="https://github.com/Nearblocks/nearblocks/assets/304265/2a87e438-8b26-431a-b280-49720a568718">

**Steps to Reproduce**

1. Go to the main page (I usually come from explorer.near.org Explorer Selector)
2. Search for any account (e.g. frol.near)
3. Hit enter
4. Sometimes it clearly hit Cloudflare protection and this may even cause a search error saying that account does not exist, at other times it renders a client-side error page, or it just hits API limits and gets stuck. I also often see "A total of 286,602,772,352 transactions found" - no way any of the accounts on NEAR has billions transactions

**Comment by andrewklau** [comment]
We've increased the rate limit and reduced cloudflare protection aggression, hope this helps. Number of constant queries have already gone up since applying this as we're battling a large number bot queries

There's some better error handling which needs to be implemented on the app side @cherrybarry

**Comment by frol** [comment]
I still experience half-loaded pages every single time I use nearblocks.

<img width="1624" alt="image" src="https://github.com/Nearblocks/nearblocks/assets/304265/a2080d69-ba17-4f3a-af33-a3011c184780">

<img width="1624" alt="image" src="https://github.com/Nearblocks/nearblocks/assets/304265/dcc57c1d-5cde-4f4e-b510-840f71327ba6">

Users also report that it never loads and I have to ask them to refresh the page several times...

**Comment by yudhomax** [comment]
Fixed in #180

**Comment by yudhomax** [comment]
Fixed in #180
