### ISSUE TITLE
API for retrieving account by public key

### ISSUE THREAD

**Issue by cherrybarry** [Nearblocks/nearblocks#16]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, the API provides functionality for retrieving public keys associated with an account. However, there is a need for an additional feature to find the account associated with a given public key

**Describe the solution you'd like**
Create a new API endpoint that accepts a public key as a parameter and returns the account associated with that public key

**Comment by andrewklau** [comment]
Could also add this to the search box
