### ISSUE TITLE
Add LNR Token

### ISSUE THREAD

**Issue by linguists** [Nearblocks/nearblocks#167]
## Legacy Token Request

**Token Information**
Token contract address: `802d89b6e511b335f05024a65161bce7efc3f311.factory.bridge.near`
Contract deployment Block number/hash: [`110,464,818`](https://nearblocks.io/txns/5hy2WgnfLtwJcipmvN2gyQW5W9jV731LcbbGRMKqHta2)

LNR is bridged from Ethereum by Rainbow Bridge. 

**How to identify Token mint**
A clear and concise description of how to identify token mints. Please provide an example transaction as well.

`mint` function called on `802d89b6e511b335f05024a65161bce7efc3f311.factory.bridge.near` by `factory.bridge.near`. The `mint` function is only callable by `factory.bridge.near`. Function call arguments: 

```
{
  "account_id": "linear.sputnik-dao.near",
  "amount": "200000000000000000000000000"
}
```

`account_id` is the receiver of `mint`

example tx: https://nearblocks.io/txns/9oQ6txoNfVgiHjgTzNsm8dzPrm6wiuNcAoYzKA6SCUkc#execution

**How to identify Token burn**
A clear and concise description of how to identify token burns. Please provide an example transaction as well.

`withdraw` function called on `802d89b6e511b335f05024a65161bce7efc3f311.factory.bridge.near` by users. Function call arguments: 

```
{
  "amount": "1000000000000000000",
  "recipient": "6e0bef2d0c48ba9f5b4d7c96b0e8cbe0c86dc5c4"
}
```

The amount of token is burnt for the caller of the `withdraw` function. 

There's no withdraw / burn example for LNR, but there should be some from other bridge tokens like USDT.e and USDC.e

**How to identify Token transfers**
A clear and concise description of how to identify token transfers. Please provide an example transaction as well.

Parse event log in `ft_transfer` or `ft_transfer_call` function: 

```
EVENT_JSON:{"standard":"nep141","version":"1.0.0","event":"ft_transfer","data":[{"old_owner_id":"3b0961e7988d78996d74cec62bf2256a84b76d2078ddae82b8dc42a69eab1525","new_owner_id":"fees.sweat","amount":"2910000000000000000","memo":"order_fee_76747"}]}
```

example tx: https://nearblocks.io/txns/BAKu7S3MyFo6WAQYAnTD1gBhQWmvGj8nZVZNjSZUcjVg#execution

**Comment by andrewklau** [comment]
All rainbow bridge tokens were added in nearblocks on bos

https://beta.nearblocks.io/token/802d89b6e511b335f05024a65161bce7efc3f311.factory.bridge.near

This will move to nearblocks.io this month

**Comment by vikpande** [comment]
@linguists , fyi as well.

**Comment by vikpande** [comment]
@linguists , @andrewklau , can you please check this and help us close the request. thank you.

**Comment by andrewklau** [comment]
We'l be moving beta to nearblocks.io in next two days so will move this to closed
