### ISSUE TITLE
Add Dark Theme 

### ISSUE THREAD

**Issue by globart** [Nearblocks/nearblocks#227]
## Feature Request

**Describe the solution you'd like**
Please add dark theme toggle/switch. 
It can be simple dark/light toggle or it can also contain use system theme.

**Describe alternatives you've considered**
Every major block explorer has this feature, you can check [Etherscan](https://etherscan.io/) or [Solscan](https://solscan.io/) for example

**Comment by andrewklau** [comment]
Closed by #268
