### ISSUE TITLE
API: block_height stuck on old block

### ISSUE THREAD

**Issue by PizBernina** [Nearblocks/nearblocks#238]
## Bug Report

**Current Behavior**
https://api.nearblocks.io/v1/blocks/latest returns an old block: 115628561

**Expected behavior/code**
Should match latest block on https://nearblocks.io/. On the webpage it seems to be the latest.

**Additional context/Screenshots**
![image](https://github.com/Nearblocks/nearblocks/assets/47326745/383bbba1-5834-4104-a2c8-6a7b24dd2773)

**Comment by andrewklau** [comment]
Hi @PizBernina 

Please try https://api3.nearblocks.io/v1/blocks/latest 

api.nearblocks.io will be redirected soon
