### ISSUE TITLE
Use wallet selector for contract connect methods

### ISSUE THREAD

**Issue by andrewklau** [Nearblocks/nearblocks#36]
As a user I would like to be able to connect my wallets other than just the old deprecated near wallet. 

Replace wallet selector with https://docs.near.org/tools/wallet-selector

<img width="974" alt="Screenshot 2023-11-01 at 22 27 44" src="https://github.com/Nearblocks/nearblocks/assets/2239920/40052b3e-2906-4f8b-a7d7-abf288e0845a">

**Comment by yudhomax** [comment]
Fixed in #172
