### ISSUE TITLE
Token Txns and NFT Token Txns tabs not updated on account change 

### ISSUE THREAD

**Issue by RezaRahemtola** [Nearblocks/nearblocks#416]
## Bug Report

**Current Behavior**
- Search for an account (ex: I searched for `gagdiez.near`: https://nearblocks.io/address/gagdiez.near
You can see the transactions, token transactions and NFT transactions fine
- In the searchbar at the top right, search for another account (ex: `rezarah.near`)
- Only the Transactions tab is updated with the new account information (even if you were on one of the other tabs). To see the values for the new account, you have to refresh the page

**Expected behavior/code**
Token and NFT transactions should be updated with those of the new account searched

**Additional context/Screenshots**
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/1514e7a7-2b25-4ba5-8256-d8c8e0ce4063">

**Comment by andrewklau** [comment]
Appears to have been an issue with stale BOS components. This should be fixed now since we dropped BOS, could you check again?
