### ISSUE TITLE
Display extra parameters on Nearblocks explorer

### ISSUE THREAD

**Issue by vikpande** [Nearblocks/nearblocks#44]
## Feature Request

**Describe the solution you'd like**
As reported by one of our partners " "I have passed title, description, extra , reference, and reference_hash as NFT metadata arguments."

For starters, if we are able to show , 1. extra , 2. reference and 3. reference_hash, that would be great.

**Comment by cherrybarry** [comment]
Hi @vikpande

Thank you for opening this feature request! We appreciate your feedback and your interest in improving NearBlocks.

We've taken note of your request to display additional parameters. Our team will review and consider them for inclusion in a future update.

**Comment by cherrybarry** [comment]
Closed by #291
