### ISSUE TITLE
Enable search by range of block height for APIs

### ISSUE THREAD

**Issue by PiVortex** [Nearblocks/nearblocks#472]
## Feature Request

Many of the API endpoints allow searching by date range. Dates may be too wide of a range for specific use cases, for example one user wanted to search by a block range for transactions to / from a contract / account. It may be beneficial to introduce searching by block height not just dates.

An example is this endpoint here https://api.nearblocks.io/api-docs/#/Account/get_v1_account__account__txns

**Comment by 19Nazar** [comment]
@andrewklau please can you tell me this issues is active?

**Comment by andrewklau** [comment]
@19Nazar this is on our todo list, do you want to pick this up?

**Comment by 19Nazar** [comment]
@andrewklau Yeah, I'd like to solve this issue

**Comment by 19Nazar** [comment]
But I have a few questions, where should I ask them?
