### ISSUE TITLE
Contract tab doesn't stable on Nearblock

### ISSUE THREAD

**Issue by haitranwang** [Nearblocks/nearblocks#473]
## Bug Report
my nearwallet in case of airdrop in the future 👯‍♂️: tranquanghai.near
**Current Behavior**
I can't interact with the contract on your Explorer
<img width="1357" alt="image" src="https://github.com/user-attachments/assets/8c1f55dc-592c-4efb-9b94-c1cfb78a5c7e">
When I ask admin your telegram, admin suggests me should reload to get Contract button, but it didn't work and I don't know why I should do this action on a PROCTION version.
<img width="945" alt="image" src="https://github.com/user-attachments/assets/36f13c74-b89a-4a6d-a0f5-395c8982a122">

**Comment by andrewklau** [comment]
This error looks to be because Read RPC (testnet) is unavailable right now. I've updated the API to return values from a different RPC.

@cherrybarry this week we should look into error handling at RPC error handling in both frontend and API. As well as pass the selected RPC to the API
