### ISSUE TITLE
NEP-518 support: add handling of `/token/0x...` routes

### ISSUE THREAD

**Issue by 2dpetkov** [Nearblocks/nearblocks#500]
## Feature Request

**Is your feature request related to a problem? Please describe.**
In order for [NEP-518](https://github.com/near/NEPs/issues/518) to facilitate a seamless user experience for Ethereum users on Near, block explorers in the ecosystem should be able to route requests in accordance to [EIP-3091](https://eips.ethereum.org/EIPS/eip-3091). 

One such UX improvement is the ability to query token information based on implicit Ethereum accounts (i.e. `0x...`) natively in nearblocks.
![telegram-cloud-photo-size-2-5409099933505676040-x](https://github.com/user-attachments/assets/ec13544b-43ac-4b9b-9f41-a820a467003d)

i.e. making sure that 
```https://nearblocks.io/token/0xaA1E7A316F17B5875e735d48A3828453C0e36711```
would display the same information or redirect to
```https://nearblocks.io/token/usdt.tether-token.near```

**Describe the solution you'd like**
To achieve this, nearblocks can make use of the `lookup` method in the [address-map.near](https://nearblocks.io/address/address-map.near?tab=contract) contract whenever the `/token` endpoint is invoked with a `0x...` address. The relationship between named and `0x...`-type addresses is
```
hex_address = "0x" + encode_to_hex(keccak256(named_address)[12:32])
```

**Comment by andrewklau** [comment]
Fixed in #517
