### ISSUE TITLE
Failed receipts showing as Successful

### ISSUE THREAD

**Issue by ewiner** [Nearblocks/nearblocks#501]
## Bug Report

**Current Behavior**

The "receipts" view and its CSV export seem to show _transaction_ status instead of receipts status.

For example:
* https://nearblocks.io/txns/8LkM4m4r8k3B9nWT6tYM9SX2yhuJUJrKLpxMXeNCUQ16#summary has a failed receipt
* But if you navigate to the receipt on https://nearblocks.io/address/v1.signer?tab=receipts or find it in the CSV download, it'll say "Success"

**Expected behavior/code**

Failed Receipts should be marked as failed on the Receipts tab & download

**Comment by andrewklau** [comment]
Fixed in #506

**Comment by ewiner** [comment]
Thanks!
