### ISSUE TITLE
I can not withdraw my token

### ISSUE THREAD

**Issue by rabbyhasan7** [Nearblocks/nearblocks#510]
## Legacy Token Request

**Token Information**UWON
Token contract address:uwon
Contract deployment Block number/hash:2fbdK1s2vGHLQSyG5ip7HJtopbZCSq3TtUmvA49e7Shy

**How to identify Token mint**
A clear and concise description of how to identify token mints. Please provide an example transaction as well.

**How to identify Token mint**
A clear and concise description of how to identify token burns. Please provide an example transaction as well.

**How to identify Token transfers**
A clear and concise description of how to identify token transfers. Please provide an example transaction as well.

**Comment by andrewklau** [comment]
NearBlocks is an independent block explorer and cannot assist with issues related to tokens, lost funds, or transactions. For support, please contact your wallet provider, exchange, or the project/contract owner, as they are best equipped to help.
