### ISSUE TITLE
Request for Refund Due to Failed Transfer of WNEAR to Binance NEAR Address

### ISSUE THREAD

**Issue by lin8734** [Nearblocks/nearblocks#514]
Dear,

I hope this message finds you well. I am writing to bring to your attention an issue I encountered during a recent transaction involving WNEAR tokens.

I withdrew my tokens and received WNEAR (wrapped NEAR) instead of NEAR. When I attempted to transfer the WNEAR tokens to my Binance NEAR wallet, the transaction failed. Upon further investigation, I realized that the final destination address was listed as "wrap.near," which appears to have caused the failure.

Given this situation, I kindly request your assistance in returning the funds to my wallet, as the transaction did not complete successfully.

Here are the details of the transaction for your reference:

Transaction Hash: [AkGn7XxD3WnttyJsJNpeVZAX8SbdBnvuMYYTRxjMLw8G]
Amount: [9.7536WNEAR]
Destination Address: [021af2ca0b2e1f45d190b32dbda28cba91bd6ef3818b75805eac52a0afae3094]
I would greatly appreciate your prompt assistance in resolving this matter and returning the funds. Please let me know if any further information is required.

Thank you for your support, and I look forward to your response.

Best regards,
[MY NEAR Wallet Address]43901dff83176d115187510084c28a6f92f6086e11ce9c842bcfd81bc99a7898

image
![image](https://github.com/user-attachments/assets/3db3d4bc-4be0-4a63-88ef-b8f11d0ab829)
![image](https://github.com/user-attachments/assets/330174ff-a877-4c64-a0b7-13d42110242e)

**Comment by andrewklau** [comment]
Hello,

Unfortunately NearBlocks is an independent block explorer and cannot assist with issues related to tokens, lost funds, or transactions. 

For support, please contact your wallet provider, exchange, or the project/contract owner, as they are best equipped to help.
