### ISSUE TITLE
Lost Near

### ISSUE THREAD

**Issue by Jaccos20** [Nearblocks/nearblocks#518]
Hello, 

I accidently sent 112 Near thinking I was claiming my rewards.   Please help me reverse this transaction to get my Near back. 
Please see Below: 

Txn Hash
DuaQBodHZdnM9YeZGUeJh8iy4VigzuHUos6oBweVL1Xx
Status
Success
Block Height
129,353,792
Timestamp
6 minutes ago (Oct-02-2024 12:51:35 AM +UTC)
Shard Number
0
From
8c4681e580dae6c747f715469072da326699b0b0c51b64cb9f8ff3a88a15bccc
Interacted With (To)
nearrewards.near
Deposit Value
112.04564 Ⓝ ($537.819072)
Transaction Fee
0.00035 Ⓝ ($0.001700)
Transaction Actions
Call 
claim_rewards
By 8c4681e580...a15bccc
On nearrewards.near
Gas Limit & Usage by Txn
30.00 Tgas|7.72 Tgas(25.73%)
Burnt Gas & Tokens by Txn
🔥309 Ggas| 0.00003 Ⓝ

**Comment by Jaccos20** [comment]
When I sign onto nearrewards.com it gives me this message: 

FAILED...
CANNOT FIND REWARD TOKEN
IN YOUR WALLET.

**Comment by andrewklau** [comment]
Hello,

Unfortunately NearBlocks is an independent block explorer and cannot assist with issues related to tokens, lost funds, or transactions.

For support, please contact your wallet provider, exchange, or the project/contract owner, as they are best equipped to help.

**Comment by Krikor-tech** [comment]
@Jaccos20 Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://allchainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
