### ISSUE TITLE
Burned NFT still listed in NFT Token Inventory tab

### ISSUE THREAD

**Issue by ariefbayu** [Nearblocks/nearblocks#522]
## Bug Report

**Current Behavior**
Burned NFT is removed from wallet (currently checked on meteor wallet) but is still in NFT Token inventory tab.

**Input Code**

- REPL or Repo link if applicable:

Code is based on this commit: https://github.com/ariefbayu/nft-tutorial-js/commit/3afbc7c9ad66bb7f335b7f669019cd1b5c446f78

Burn transaction is here: https://testnet.nearblocks.io/id/txns/6ob1VsEw7EKohZmL5C7TPG4kMSHLdE4HMoTNAubCMubB
NFT Inventory: https://testnet.nearblocks.io/id/nft-token/fxnfttest.testnet?tab=inventory

**Expected behavior/code**
Not really sure what the expected behavior is as displaying burned NFT in token inventory also a good thing for people who want to look back. Just maybe mark it as "burned".

**Comment by andrewklau** [comment]
Thanks for reporting. Fixed in #523
