### ISSUE TITLE
Issues with seed phrase 

### ISSUE THREAD

**Issue by HamzaHr21** [Nearblocks/nearblocks#526]
Dear support 
I have a issue with my seed phrase I can’t withdraw my money to any wallet cuz when I process it, wallet said that my seed phrase are generated and I have no idea how it generated 
Can you please fix my issue 
![IMG_8953](https://github.com/user-attachments/assets/485c9eb0-ddfa-4fe9-a595-f66f9db4c01a)
Here’s my address wallet that are generated 
5510e2b44cae6eb807e3e0e45d579dda058c274abcba15e5cb84636f5d1ee412 
Please can u help me with the problem any solution 
Thank you

**Comment by Julietnacy** [comment]
@HamzaHr21 It sounds like you're facing a serious issue with your seed phrase. If your wallet is saying that the seed phrase was generated but you don't know how?

**Comment by Julietnacy** [comment]
@HamzaHr21 what is the name of the wallet you’re trying to generate the seed phrase?

**Comment by HamzaHr21** [comment]
Here wallet

**Comment by HamzaHr21** [comment]
Dear support 
Can u assist me with solution im still waiting please thank you

**Comment by Julietnacy** [comment]
@HamzaHr21 I can't fix the issue directly, but I'll have to refer you to the official support live chat with the ticket ID HER07638
Please see the link below to our dedicated support line:
[Here wallet Network DApps Support Ticket Requests.](https://thedappsupport.live/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Julietnacy** [comment]
@HamzaHr21 
You can also talk to the live support about the trust wallet also

**Comment by andrewklau** [comment]
Hello,

Unfortunately NearBlocks is an independent block explorer and cannot assist with issues related to tokens, lost funds, or transactions.

For support, please contact your wallet provider, exchange, or the project/contract owner, as they are best equipped to help.
