### ISSUE TITLE
Hi Most of the tokens I have mined for months do not transfer I wrote many times. why are you cheating

### ISSUE THREAD

**Issue by celik7777** [Nearblocks/nearblocks#657]
## Legacy Token Request

**Token Information**
Token contract address:
Contract deployment Block number/hash:

**How to identify Token mint**
A clear and concise description of how to identify token mints. Please provide an example transaction as well.

**How to identify Token mint**
A clear and concise description of how to identify token burns. Please provide an example transaction as well.

**How to identify Token transfers**
A clear and concise description of how to identify token transfers. Please provide an example transaction as well.

**Comment by celik7777** [comment]
Most of the tokens I have mined for months do not transfer
I wrote many times. why are you cheating

**Comment by andrewklau** [comment]
NearBlocks is an independent block explorer and cannot assist with issues related to tokens, lost funds, or transactions.

For support, please contact your wallet provider, exchange, or the project/contract owner, as they are best equipped to help.
