### ISSUE TITLE
Fraud

### ISSUE THREAD

**Issue by Dimaaan33** [Nearblocks/nearblocks#663]
On the website nearmp.net scammers are working under the guise of your platform.I invested $3,000 there

**Comment by andrewklau** [comment]
NearBlocks is an independent block explorer and cannot assist with issues related to tokens, lost funds, or transactions.

For support, please contact your wallet provider, exchange, or the project/contract owner, as they are best equipped to help.

**Comment by Dimaaan33** [comment]
good time of day.Earlier, you wrote that it is possible to return funds by opening a dispute and forming an application for your fraudster validator.
