### ISSUE TITLE
Wrong adress send

### ISSUE THREAD

**Issue by Cryptotoutard** [Nearblocks/nearblocks#679]

**Comment by Cryptotoutard** [comment]
M

> Bonjour
> 
> je vous signale que je me suis trompé de adresse en retirant de wexc vers Best Wallet. Merci de voir la transaction ci-jointe . L’adresse a laquelle la transaction devait être envoyé est :
> 
> 0x5fb2aec707f428e38d44106f405b9b296793e025
>

**Comment by Hinted-tech** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[NearBlocks  Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
