### ISSUE TITLE
Wrong Transaction

### ISSUE THREAD

**Issue by HenryB98** [Nearblocks/nearblocks#688]
I mistakenly sent 1.7 NEAR  from my wallet: henryb98.near to this Near wallet address: 8db2a34815cc77054cd9ab7cafbeeb025dd59006e20b7011409429abfc1f1e1b
Can i get it back? 🙏

**Comment by hanKah37De** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [NEARBLOCKS SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
