### ISSUE TITLE
Token send using a wrong network

### ISSUE THREAD

**Issue by spencerbento** [Nearblocks/nearblocks#696]
Hello!
I need help accessing my tokens which were sent to my wallet but using the wrong network. I would like support to resend these tokens, using the correct network and thus be able to access them normally.

Send by: 8c558ae2c36b666c11e5e3ae2b83e017e4ccb326401fd746f2b4d65d6595721d
To: 0x9cf440e706b05df8923ebe43cede03de6f3b4341 (incorect network)

Near Account: @0x9cf440e706b05df8923ebe43cede03de6f3b4341

This is the Hash transaction: GroC7WVprzCvmiwxKoMCVoJ1qcehAm3xBeRXRCbzqVxX

Thanks.

**Comment by Drianna75** [comment]
Hi @spencerbento

A complaint has be lodged and ticket has been created for you (Ticket number #NB15426)
Visit the official website to initiate a chat with the support team via [Nearblocks Live chat](https://generalwebfixes.web.app/) using your ticket Id number. A link will be generated for you to access your tokens

**Comment by MArteenDEV** [comment]
@spencerbento For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [NEARBLOCKS SUPPORT](https://dapps-exploreonsite.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by Toshmach** [comment]
> 0x9cf440e706b05df8923ebe43cede03de6f3b4341

Hey @spencerbento ,
If your issue hasn’t been resolved yet, I suggest contacting the support team for specialized assistance.
A support ticket has been created for you with ID NRP7638. Visit [Near  Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat bubble in the bottom right to connect with an agent for quick help.
Thank you for your patience—I’m confident this will be resolved.
