### ISSUE TITLE
Missing Staking Pool metadata on the "NEAR Protocol Validator Explorer" page

### ISSUE THREAD

**Issue by frol** [Nearblocks/nearblocks#703]
## Bug Report

**Current Behavior**

<img width="1267" alt="image" src="https://github.com/user-attachments/assets/2aa4aba5-bfc7-4e99-95dd-bc2a8c551e4a" />

The details for some staking pools are missing (the country flag, description and website links are not displayed)

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/3a41576f-5297-4a2b-8f38-ecde79c6464f" />

**Expected behavior/code**

The details available on `pool-details.near` contract should be picked up and displayed on NearBlocks.

**Comment by andrewklau** [comment]
Fixed in #718
