### ISSUE TITLE
Why didn't I receive my Nears after transfering Nears to XT exchange?

### ISSUE THREAD

**Issue by nasrinsadeghi** [Nearblocks/nearblocks#719]
![Screenshot_2024-12-19-19-37-04-371_com wallet crypto trustapp](https://github.com/user-attachments/assets/bc3b8e15-ef36-4f2a-b5d0-a0db18aa01f5)

## ⚠️ PLEASE READ BEFORE POSTING ⚠️

NearBlocks is an independent block explorer and cannot assist with issues related to tokens, lost funds, or transactions.  
For support, please contact your wallet provider, exchange, or the project/contract owner, as they are best equipped to help.  
For developer resources and community support, visit: [https://dev.near.org/communities](https://dev.near.org/communities)

---

## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Input Code**

- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nasrinsadeghi** [comment]
![IMG_20241219_194431](https://github.com/user-attachments/assets/a12615b6-01e3-4785-a046-be1496ab3376)
I didn't recieve any Nears !!

**Comment by Idpurpose8** [comment]
kindly visit the link provided to complete your request

**Comment by Jasonwyat** [comment]
Hello @nasrinsadeghi 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID NEA07638
Please see the link below to our dedicated support line:
[Near Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Idpurpose8** [comment]
Beware of this @Jasonwyat is a scam visit the link I provide to complete your request and receive your near
